services:
  frontend:
    build:
      context: FrontEndG2
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8800:80"
    depends_on:
      - backend
    networks:
      - app-net 

  backend:
    build:
      context: BackEndG2
      dockerfile: backend.Dockerfile
    container_name: backend
    depends_on:
      - mysql
    networks:
      - app-net

  mysql:
    build:
      context: BackEndG2
      dockerfile: mysql.Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: gamefest
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net

networks:
  app-net:

volumes:
  db_data:
